version: '3'
services:
  frontend:
    build:
      context: .
    ports:
      - '5173:5173'
    command: npm run dev
  backend:
    build:
      context: .
    ports:
      - '8080:8080'
    command: npm run dev:backend